In [1]:
import numpy as np
import pandas as pd
from src.modules import *

In [2]:
import os

In [3]:
irs_folder_path = 'data/irs_data/'
house_data_path = 'data/formatted_house_totals/'

irs_files = [file for file in os.listdir(irs_folder_path) if os.path.isfile(os.path.join(irs_folder_path, file))]
house_data_files = [file for file in os.listdir(house_data_path) if os.path.isfile(os.path.join(house_data_path, file))]

In [4]:
house_data_files

['IL_House_12.csv',
 'IL_House_14.csv',
 'IL_House_16.csv',
 'IL_House_18.csv',
 'IL_House_20.csv',
 'OH_House_12.csv',
 'OH_House_14.csv',
 'OH_House_16.csv',
 'OH_House_18.csv',
 'OH_House_20.csv',
 'WI_House_12.csv',
 'WI_House_14.csv',
 'WI_House_16.csv',
 'WI_House_18.csv',
 'WI_House_20.csv']

In [5]:
irs_files

['irs_count_2012_f.csv',
 'irs_count_2012_f_d.csv',
 'irs_count_2014_f.csv',
 'irs_count_2014_f_d.csv',
 'irs_count_2016_f.csv',
 'irs_count_2016_f_d.csv',
 'irs_count_2018_f.csv',
 'irs_count_2018_f_d.csv',
 'irs_count_2020_f.csv',
 'irs_count_2020_f_d.csv']

In [6]:
# for i in house_data_files:
#     state = i[0:2] #first two letters of the filename, corresponding to the state abbv.
#     year = i[-6:-4] #two digit year 
    
#     # Import house file
#     house = pd.read_csv(f'{house_data_path}{i}')
    
#     # Import IRS file corresponding to the year obtained from the filename of the house file
#     irs = pd.read_csv(f'{irs_folder_path}irs_count_20{year}_f.csv')
    
#     # Get IRS data only for the relevant state (this is done to ensure that states with identicle county names do not hav their data mixed)
#     irs_state = irs.loc[irs['STATE']==state]
#     irs_county = irs_state['COUNTYNAME'].tolist()
#     irs_county = [i.lower() for i in remove_keyword(irs_county,'County')] # format to match the House data
#     irs_copy = irs_state.copy() #avoid setting a value on a copy of a slice
#     irs_copy['COUNTYNAME'] = irs_county
    
#     #
#     irs_merge = house.merge(irs_state, left_on='County', right_on='COUNTYNAME')
    
#     #Folder to store these new dataframes in
#     new_folder_path = 'data/house_fec_irs_joined/'
    
#     # Create the directory if it doesn't exist
#     os.makedirs(new_folder_path, exist_ok=True)
    
#     # Save the DataFrames as CSV files
#     csv_filename_f = f'{i[:-4]}_irs.csv'
#     irs_merge.to_csv(os.path.join(new_folder_path, csv_filename_f), index=False) #the 'final' formatted files, with election and IRS data combined

In [7]:
for i in house_data_files:
    state = i[0:2] #first two letters of the filename, corresponding to the state abbv.
    year = i[-6:-4] #two digit year 
    
    # Import house file
    house = pd.read_csv(f'{house_data_path}{i}')
    
    # Import IRS file corresponding to the year obtained from the filename of the house file
    irs = pd.read_csv(f'{irs_folder_path}irs_count_20{year}_f.csv')
    
    # Get IRS data only for the relevant state (this is done to ensure that states with identicle county names do not hav their data mixed)
    irs_state = irs.loc[irs['STATE']==state]
    irs_county = irs_state['COUNTYNAME'].tolist()
    irs_county = [i.lower() for i in remove_keyword(irs_county,'County')] # format to match the House data
    
    #These two counties are misnamed in the IRS data
    irs_misnamed = {'de witt':'dewitt','jo daviess':'jodaviess'}
    cor_counties = [irs_misnamed.get(item, item) for item in irs_county]
    
    irs_copy = irs_state.copy() #avoid setting a value on a copy of a slice
    irs_copy['COUNTYNAME'] = cor_counties

    irs_merge = house.merge(irs_copy, left_on='County', right_on='COUNTYNAME')
    
    #drop columns for no-longer useful data,
    # In this case we don't need county names twice
    irs_export = irs_merge.drop('COUNTYNAME',axis=1)
    #Folder to store these new dataframes in
    new_folder_path = 'data/house_fec_irs_joined/'
    
    # Create the directory if it doesn't exist
    os.makedirs(new_folder_path, exist_ok=True)
    
    # Save the DataFrames as CSV files
    csv_filename_f = f'{i[:-4]}_irs.csv'
    irs_export.to_csv(os.path.join(new_folder_path, csv_filename_f), index=False) #the 'final' formatted files, with election and IRS data combined

In [88]:
for i in house_data_files:
    state = i[0:2] #first two letters of the filename, corresponding to the state abbv.
    year = i[-6:-4] #two digit year 
    
    # Import house file
    house = pd.read_csv(f'{house_data_path}{i}')
    
    # Import IRS file corresponding to the year obtained from the filename of the house file
    irs = pd.read_csv(f'{irs_folder_path}irs_count_20{year}_f_d.csv')
    
    # Get IRS data only for the relevant state (this is done to ensure that states with identicle county names do not hav their data mixed)
    irs_state = irs.loc[irs['STATE']==state]
    irs_county = irs_state['COUNTYNAME'].tolist()
    irs_county = [i.lower() for i in remove_keyword(irs_county,'County')] # format to match the House data

        
    #These two counties are misnamed in the IRS data
    irs_misnamed = {'de witt':'dewitt','jo daviess':'jodaviess'}
    cor_counties = [irs_misnamed.get(item, item) for item in irs_county]
    
    irs_copy = irs_state.copy() #avoid setting a value on a copy of a slice
    irs_copy['COUNTYNAME'] = cor_counties

    irs_merge = house.merge(irs_copy, left_on='County', right_on='COUNTYNAME')
    
    #drop columns for no-longer useful data,
    # In this case we don't need county names twice
    irs_export = irs_merge.drop('COUNTYNAME', axis=1)
    #Folder to store these new dataframes in
    new_folder_path = 'data/house_fec_irs_joined/'
    
    # Create the directory if it doesn't exist
    os.makedirs(new_folder_path, exist_ok=True)
    
    # Save the DataFrames as CSV files
    csv_filename_f = f'{i[:-4]}_irs_d.csv'
    irs_export.to_csv(os.path.join(new_folder_path, csv_filename_f), index=False) #the 'final' formatted files, with election and IRS data combined

In [9]:
il_irs_12 = pd.read_csv(f'{irs_folder_path}{irs_files[0]}')

In [10]:
il_irs_12 = il_irs_12.loc[il_irs_12['STATE']=='IL']

In [11]:
il_irs_12

,STATE,COUNTYNAME,N1,MARS1,MARS2,MARS4,PREP,N2,NUMDEP,A00100,...,N11070,A11070,N06500,A06500,N10300,A10300,N11901,A11901,N11902,A11902
595,IL,Adams County,32050.0,15060.0,13240.0,3330.0,21890.0,60530.0,17960.0,1662924.0,...,3560.0,4289.0,22050.0,183545.0,23460.0,194593.0,4920.0,26296.0,25140.0,61937.0
596,IL,Alexander County,2770.0,1020.0,960.0,720.0,1760.0,5730.0,2090.0,93113.0,...,670.0,766.0,1530.0,7086.0,1750.0,7716.0,330.0,899.0,2340.0,6639.0
597,IL,Bond County,7100.0,3010.0,3300.0,720.0,4940.0,14020.0,4170.0,334316.0,...,800.0,973.0,4790.0,31530.0,5230.0,33931.0,1120.0,4368.0,5510.0,14271.0
598,IL,Boone County,25050.0,10100.0,11030.0,3600.0,14130.0,55560.0,21630.0,1453181.0,...,3890.0,6454.0,16480.0,162263.0,17580.0,169387.0,3300.0,17336.0,20540.0,60682.0
599,IL,Brown County,2370.0,1110.0,1020.0,200.0,1810.0,4480.0,1290.0,114205.0,...,220.0,291.0,1670.0,11153.0,1800.0,12038.0,430.0,2309.0,1790.0,4546.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,IL,Whiteside County,28090.0,12680.0,11620.0,3440.0,16420.0,54130.0,16490.0,1357519.0,...,3270.0,4090.0,18980.0,140869.0,20040.0,150149.0,3980.0,29380.0,22540.0,56926.0
693,IL,Will County,317440.0,135420.0,134900.0,42260.0,180290.0,679410.0,257310.0,21266799.0,...,36580.0,51112.0,224070.0,2581100.0,238870.0,2674378.0,44670.0,213453.0,259140.0,809530.0
694,IL,Williamson County,30080.0,12890.0,12750.0,4010.0,16310.0,58510.0,17620.0,1442126.0,...,3900.0,4661.0,20280.0,149243.0,21880.0,158457.0,4260.0,15144.0,24210.0,62266.0
695,IL,Winnebago County,135890.0,61110.0,49810.0,23010.0,72760.0,269910.0,93220.0,6771870.0,...,21170.0,28202.0,88110.0,721835.0,96270.0,756337.0,16890.0,74259.0,112460.0,305513.0
696,IL,Woodford County,18210.0,7570.0,9190.0,1270.0,10090.0,37330.0,11830.0,1331285.0,...,1320.0,1708.0,13800.0,177929.0,14400.0,186742.0,3540.0,28420.0,13680.0,37336.0

In [83]:
irs_county = il_irs_12['COUNTYNAME'].tolist()
irs_county = [i.lower() for i in remove_keyword(irs_county,'County')]
il_irs_12['COUNTYNAME'] = irs_county

In [75]:
irs_county2 = [i.lower() for i in remove_keyword(irs_county,'County')]

In [84]:
irs_county

['adams',
 'alexander',
 'bond',
 'boone',
 'brown',
 'bureau',
 'calhoun',
 'carroll',
 'cass',
 'champaign',
 'christian',
 'clark',
 'clay',
 'clinton',
 'coles',
 'cook',
 'crawford',
 'cumberland',
 'dekalb',
 'de witt',
 'douglas',
 'dupage',
 'edgar',
 'edwards',
 'effingham',
 'fayette',
 'ford',
 'franklin',
 'fulton',
 'gallatin',
 'greene',
 'grundy',
 'hamilton',
 'hancock',
 'hardin',
 'henderson',
 'henry',
 'iroquois',
 'jackson',
 'jasper',
 'jefferson',
 'jersey',
 'jo daviess',
 'johnson',
 'kane',
 'kankakee',
 'kendall',
 'knox',
 'lake',
 'lasalle',
 'lawrence',
 'lee',
 'livingston',
 'logan',
 'mcdonough',
 'mchenry',
 'mclean',
 'macon',
 'macoupin',
 'madison',
 'marion',
 'marshall',
 'mason',
 'massac',
 'menard',
 'mercer',
 'monroe',
 'montgomery',
 'morgan',
 'moultrie',
 'ogle',
 'peoria',
 'perry',
 'piatt',
 'pike',
 'pope',
 'pulaski',
 'putnam',
 'randolph',
 'richland',
 'rock island',
 'st. clair',
 'saline',
 'sangamon',
 'schuyler',
 'scott',
 'shelby',
 'stark',
 'stephenson',
 'tazewell',
 'union',
 'vermilion',
 'wabash',
 'warren',
 'washington',
 'wayne',
 'white',
 'whiteside',
 'will',
 'williamson',
 'winnebago',
 'woodford']

In [12]:
IL_12 = pd.read_csv(f'{house_data_path}{house_data_files[0]}')

In [15]:
OH_12 = pd.read_csv(f'{house_data_path}{house_data_files[5]}')

In [16]:
OH_12.describe()

,D0,D1,OTHER0,R0,R1
count,88.000000,88.000000,88.000000,88.000000,88.000000
mean,17388.659091,41420.625000,1222.045455,34640.818182,22813.670455
std,38516.650126,100980.934477,2638.215580,51117.394809,30352.455138
min,0.000000,2127.000000,0.000000,2679.000000,0.000000
25%,4215.750000,5726.750000,0.000000,9395.500000,7162.500000
50%,6581.000000,10355.500000,0.000000,15169.500000,12622.000000
75%,16000.500000,30025.250000,998.250000,33521.000000,22537.000000
max,302619.000000,797772.000000,15850.000000,277196.000000,149229.000000

In [14]:
IL_12.describe()

                  D0            D1        OTHER0             R0             R1
count     102.000000  1.020000e+02    102.000000     102.000000     102.000000
mean    13740.627451  1.131230e+04   1312.647059    6915.411765   14462.421569
std     27618.129163  1.098924e+05   8560.821947   34158.735913   28952.339018
min         0.000000  0.000000e+00      0.000000       0.000000       0.000000
25%      1828.500000  0.000000e+00      0.000000       0.000000    1856.750000
50%      3554.000000  0.000000e+00      0.000000       0.000000    4839.000000
75%      9188.500000  0.000000e+00    192.000000    1297.500000   11987.500000
max    168250.000000  1.109781e+06  86126.000000  335037.000000  191617.000000

In [51]:

house = IL_12
irs = il_irs_12
irs_state = irs.loc[irs['STATE']=='IL']
irs_county = irs_state['COUNTYNAME'].tolist()
irs_county = [i.lower() for i in remove_keyword(irs_county,'County')]
irs_state['COUNTYNAME'] = irs_county
irs_merge = house.merge(irs_state, left_on='County', right_on='COUNTYNAME')

# #Folder to store these new dataframes in
# new_folder_path = 'data/house_fec_irs_joined/'

# # Create the directory if it doesn't exist
# os.makedirs(new_folder_path, exist_ok=True)

# # Save the DataFrames as CSV files
# csv_filename_f = f'{i[:-4]}_irs.csv'
# irs_merge.to_csv(os.path.join(new_folder_path, csv_filename_f), index=False) #the 'final' formatted files, with election and IRS data combined

In [52]:
m_county = irs_merge['County'].tolist()

In [56]:
len(m_county)

100

In [55]:
h_list = house['County'].tolist()
len(h_list)

102

In [57]:
n = set(h_list) - set(m_county)

In [58]:
n

{'dewitt', 'jodaviess'}

In [32]:
i_list2 = irs['COUNTYNAME'].tolist()
i_list

['Adams County',
 'Alexander County',
 'Bond County',
 'Boone County',
 'Brown County',
 'Bureau County',
 'Calhoun County',
 'Carroll County',
 'Cass County',
 'Champaign County',
 'Christian County',
 'Clark County',
 'Clay County',
 'Clinton County',
 'Coles County',
 'Cook County',
 'Crawford County',
 'Cumberland County',
 'DeKalb County',
 'De Witt County',
 'Douglas County',
 'DuPage County',
 'Edgar County',
 'Edwards County',
 'Effingham County',
 'Fayette County',
 'Ford County',
 'Franklin County',
 'Fulton County',
 'Gallatin County',
 'Greene County',
 'Grundy County',
 'Hamilton County',
 'Hancock County',
 'Hardin County',
 'Henderson County',
 'Henry County',
 'Iroquois County',
 'Jackson County',
 'Jasper County',
 'Jefferson County',
 'Jersey County',
 'Jo Daviess County',
 'Johnson County',
 'Kane County',
 'Kankakee County',
 'Kendall County',
 'Knox County',
 'Lake County',
 'LaSalle County',
 'Lawrence County',
 'Lee County',
 'Livingston County',
 'Logan County',
 'McDonough County',
 'McHenry County',
 'McLean County',
 'Macon County',
 'Macoupin County',
 'Madison County',
 'Marion County',
 'Marshall County',
 'Mason County',
 'Massac County',
 'Menard County',
 'Mercer County',
 'Monroe County',
 'Montgomery County',
 'Morgan County',
 'Moultrie County',
 'Ogle County',
 'Peoria County',
 'Perry County',
 'Piatt County',
 'Pike County',
 'Pope County',
 'Pulaski County',
 'Putnam County',
 'Randolph County',
 'Richland County',
 'Rock Island County',
 'St. Clair County',
 'Saline County',
 'Sangamon County',
 'Schuyler County',
 'Scott County',
 'Shelby County',
 'Stark County',
 'Stephenson County',
 'Tazewell County',
 'Union County',
 'Vermilion County',
 'Wabash County',
 'Warren County',
 'Washington County',
 'Wayne County',
 'White County',
 'Whiteside County',
 'Will County',
 'Williamson County',
 'Winnebago County',
 'Woodford County']