In [19]:
import numpy as np
import pandas as pd
from src.modules import *

In [3]:
ohio_2014_path = 'data/ohio 2014precinct.xlsx'
excel_2014 = pd.ExcelFile(ohio_2014_path)
sheet_names = excel_2014.sheet_names

In [4]:
for i in sheet_names:
    print(i)

Precinct-by-Precinct Results

In [5]:
data = pd.read_excel(ohio_2014_path, sheet_name='Precinct-by-Precinct Results', header=1)

In [27]:
data

,Edward FitzGerald,John Kasich,Anita Rios,Mike DeWine,David Pepper,Bob Bridges,John Patrick Carney,Dave Yost,Jon Husted,Kevin Knedler,...,Anthony Kendell,Patricia A. Myers,Donnie Barrera,Lawrence A. Dordea,George T. Maier,Rachael S. Gilroy,Angela S. McQuillen,Pam Ferrell,James N. Bahnsen,Char Lee
County,,,,,,,,,,,,,,,,,,,,,
Adams,1462,4499,139,4250,1862,312,1540,4186,4311,286,...,0,0,0,0,0,0,0,0,0,0
Allen,7091,19587,581,19753,7432,1466,7291,18042,19744,1256,...,0,0,0,0,0,21679,0,0,0,0
Ashland,3177,11267,405,11015,3774,802,3476,10229,10486,773,...,0,0,0,0,0,0,11891,0,0,0
Ashtabula,10082,15390,964,16013,10425,1339,10632,14202,14428,1585,...,0,0,0,0,0,0,0,0,0,0
Athens,7855,5589,964,6119,8274,826,7761,5272,5531,766,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Washington,5659,12152,525,11949,6350,958,5914,11040,10992,870,...,0,0,0,0,0,0,0,0,0,0
Wayne,5951,19962,828,19579,7135,1199,7181,18081,18971,1137,...,0,0,0,0,0,0,0,0,0,0
Williams,2245,7066,304,6835,2789,602,2336,6470,7174,451,...,0,0,0,0,0,0,0,0,0,0
Wood,11482,22296,1264,21863,13172,2398,12132,19461,22099,2008,...,0,0,0,0,0,0,0,0,0,0
Wyandot,1129,4406,156,4272,1441,337,1295,3977,4232,314,...,0,0,0,0,0,0,0,0,0,0

In [7]:
data = data.drop([0]).copy()

In [9]:
candidates = [i for i in data.columns if i.endswith(')')] #this will remove general information about the election, we only want the details about each canddidate

In [10]:
keep_cols = [data.columns[0]] + candidates #add in the column for the county names to the columns for candidates

In [13]:
data = data[keep_cols] #reduce the dataframe to just the information we need

In [20]:
data.columns = trim_party(data.columns) #apply trim_party to get just candidate names

In [24]:
county_col = data.columns[0]

In [25]:
data = data.groupby(county_col).sum()