In [1]:
import numpy as np
import pandas as pd

In [2]:
all_elec_data = pd.read_csv('data/Election Results 1976-2022-house.csv')

In [3]:
all_elec_data.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,runoff,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version,fusion_ticket
0,1976,ALABAMA,AL,1,63,41,US HOUSE,1,GEN,False,False,BILL DAVENPORT,DEMOCRAT,False,TOTAL,58906,157170,False,20230706,False
1,1976,ALABAMA,AL,1,63,41,US HOUSE,1,GEN,False,False,JACK EDWARDS,REPUBLICAN,False,TOTAL,98257,157170,False,20230706,False
2,1976,ALABAMA,AL,1,63,41,US HOUSE,1,GEN,False,False,WRITEIN,NaN,True,TOTAL,7,157170,False,20230706,False
3,1976,ALABAMA,AL,1,63,41,US HOUSE,2,GEN,False,False,J CAROLE KEAHEY,DEMOCRAT,False,TOTAL,66288,156362,False,20230706,False
4,1976,ALABAMA,AL,1,63,41,US HOUSE,2,GEN,False,False,"WILLIAM L ""BILL"" DICKINSON",REPUBLICAN,False,TOTAL,90069,156362,False,20230706,False

In [4]:
elec_2010 = all_elec_data.loc[all_elec_data['year']==2010]

In [5]:
elec_2010.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,runoff,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version,fusion_ticket
22553,2010,ALABAMA,AL,1,63,41,US HOUSE,1,GEN,NaN,False,DAVID WALTER,CONSTITUTION,False,TOTAL,26357,156281,False,20230706,False
22554,2010,ALABAMA,AL,1,63,41,US HOUSE,1,GEN,NaN,False,JO BONNER,REPUBLICAN,False,TOTAL,129063,156281,False,20230706,False
22555,2010,ALABAMA,AL,1,63,41,US HOUSE,1,GEN,NaN,False,WRITEIN,NaN,True,TOTAL,861,156281,False,20230706,False
22556,2010,ALABAMA,AL,1,63,41,US HOUSE,2,GEN,NaN,False,BOBBY BRIGHT,DEMOCRAT,False,TOTAL,106865,219028,False,20230706,False
22557,2010,ALABAMA,AL,1,63,41,US HOUSE,2,GEN,NaN,False,MARTHA ROBY,REPUBLICAN,False,TOTAL,111645,219028,False,20230706,False

In [6]:
elec_2010['state_po'].unique()

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI',
       'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA', 'MI',
       'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY', 'NC',
       'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT',
       'VT', 'VA', 'WA', 'WV', 'WI', 'WY'], dtype=object)

In [18]:
elec_2010.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1500 entries, 22553 to 24052
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   year            1500 non-null   int64
 1   state           1500 non-null   object
 2   state_po        1500 non-null   object
 3   state_fips      1500 non-null   int64
 4   state_cen       1500 non-null   int64
 5   state_ic        1500 non-null   int64
 6   office          1500 non-null   object
 7   district        1500 non-null   int64
 8   stage           1500 non-null   object
 9   runoff          0 non-null      object
 10  special         1500 non-null   bool
 11  candidate       1500 non-null   object
 12  party           1311 non-null   object
 13  writein         1500 non-null   bool
 14  mode            1500 non-null   object
 15  candidatevotes  1500 non-null   int64
 16  totalvotes      1500 non-null   int64
 17  unofficial      1500 non-null   bool
 18  version         1500 non-null   int64
 19  fusion_ticket   1500 non-null   bool
dtypes: bool(4), int64(8), object(8)
memory usage: 205.1+ KB

In [19]:
elec_2010['stage'].unique()

array(['GEN'], dtype=object)

In [21]:
elec_2010['candidate'].nunique()

1294

In [11]:
house_OH_elec_2010 = elec_2010.loc[elec_2010['state_po']=='OH']

In [8]:
house_cand_2010= pd.read_csv('house_cand_2010.csv')

In [12]:
house_cand_OH_2010 = house_cand_2010.loc[house_cand_2010['STATE ABBREVIATION']=="OH"]

In [22]:
house_cand_2010.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1521 entries, 0 to 1520
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    1521 non-null   int64
 1   STATE ABBREVIATION            1521 non-null   object
 2   DISTRICT                      1521 non-null   object
 3   CANDIDATE NAME (First)        1521 non-null   object
 4   CANDIDATE NAME (Last)         1521 non-null   object
 5   CANDIDATE NAME (Last, First)  1521 non-null   object
 6   PARTY                         1521 non-null   object
 7   INCUMBENT INDICATOR (I)       1521 non-null   int64
 8   GENERAL                       1521 non-null   object
dtypes: int64(2), object(7)
memory usage: 107.1+ KB

In [15]:
house_cand_OH_2010.info()

<class 'pandas.core.frame.DataFrame'>
Index: 59 entries, 1080 to 1138
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Unnamed: 0                    59 non-null     int64
 1   STATE ABBREVIATION            59 non-null     object
 2   DISTRICT                      59 non-null     object
 3   CANDIDATE NAME (First)        59 non-null     object
 4   CANDIDATE NAME (Last)         59 non-null     object
 5   CANDIDATE NAME (Last, First)  59 non-null     object
 6   PARTY                         59 non-null     object
 7   INCUMBENT INDICATOR (I)       59 non-null     int64
 8   GENERAL                       59 non-null     object
dtypes: int64(2), object(7)
memory usage: 4.6+ KB

In [16]:
house_cand_OH_2010.head()

,Unnamed: 0,STATE ABBREVIATION,DISTRICT,CANDIDATE NAME (First),CANDIDATE NAME (Last),"CANDIDATE NAME (Last, First)",PARTY,INCUMBENT INDICATOR (I),GENERAL
1080,1237,OH,01,Steve,Chabot,"Chabot, Steve",REP,0,103770
1081,1238,OH,01,Steve,Driehaus,"Driehaus, Steve",DEM,1,92672
1082,1239,OH,01,Jim,Berns,"Berns, Jim",LIB,0,3076
1083,1240,OH,01,Rich,Stevenson,"Stevenson, Rich",GRE,0,2000
1084,1241,OH,02,Jean,Schmidt,"Schmidt, Jean",REP,1,139027

In [23]:
house_OH_elec_2010.head()

,year,state,state_po,state_fips,state_cen,state_ic,office,district,stage,runoff,special,candidate,party,writein,mode,candidatevotes,totalvotes,unofficial,version,fusion_ticket
23600,2010,OHIO,OH,39,31,24,US HOUSE,1,GEN,NaN,False,JIM BERNS,LIBERTARIAN,False,TOTAL,3076,201518,False,20230706,False
23601,2010,OHIO,OH,39,31,24,US HOUSE,1,GEN,NaN,False,RICH STEVENSON,GREEN,False,TOTAL,2000,201518,False,20230706,False
23602,2010,OHIO,OH,39,31,24,US HOUSE,1,GEN,NaN,False,STEVE CHABOT,REPUBLICAN,False,TOTAL,103770,201518,False,20230706,False
23603,2010,OHIO,OH,39,31,24,US HOUSE,1,GEN,NaN,False,STEVE DRIEHAUS,DEMOCRAT,False,TOTAL,92672,201518,False,20230706,False
23604,2010,OHIO,OH,39,31,24,US HOUSE,2,GEN,NaN,False,JEAN SCHMIDT,REPUBLICAN,False,TOTAL,139027,237845,False,20230706,False