In [1]:
import numpy as np
import pandas as pd

In [2]:
ohio_2010_path = 'data/ohio 2010precinct.xlsx'
excel_2010 = pd.ExcelFile(ohio_2010_path)
sheet_names = excel_2010.sheet_names

In [3]:
for sheet_name in sheet_names:
    print(sheet_name)

AllCounties
Adams
Allen
Ashland
Ashtabula
Athens
Auglaize
Belmont
Brown
Butler
Carroll
Champaign
Clark
Clermont
Clinton
Columbiana
Coshocton
Crawford
Cuyahoga
Darke
Defiance
Delaware
Erie
Fairfield
Fayette
Franklin
Fulton
Gallia
Geauga
Greene
Guernsey
Hamilton
Hancock
Hardin
Harrison
Henry
Highland
Hocking
Holmes
Huron
Jackson
Jefferson
Knox
Lake
Lawrence
Licking
Logan
Lorain
Lucas
Madison
Mahoning
Marion
Medina
Meigs
Mercer
Miami
Monroe
Montgomery
Morgan
Morrow
Muskingum
Noble
Ottawa
Paulding
Perry
Pickaway
Pike
Portage
Preble
Putnam
Richland
Ross
Sandusky
Scioto
Seneca
Shelby
Stark
Summit
Trumbull
Tuscarawas
Union
Van Wert
Vinton
Warren
Washington
Wayne
Williams
Wood
Wyandot

In [4]:
all_county_2010 = 'AllCounties'

In [5]:
df = pd.read_excel(ohio_2010_path, sheet_name=all_county_2010, header=1)

In [6]:
#get only the totals for each county
df_tot = df[(df['PRECINCT_NAME'].str.contains('total',case=False,na=False))]

In [13]:
#create list of all county names and columns containing data from house races
house_col = [col for col in df_tot if col.startswith('COUNTY NAME') or col.startswith('U.S. Representative')]

In [11]:
df_house = df_tot[house_col]

In [12]:
df_house

,COUNTY NAME,"U.S. Representative - District 02 - Conover, Randy","U.S. Representative - District 02 - Johnston, Marc","U.S. Representative - District 02 - Schmidt, Jean","U.S. Representative - District 02 - Yalamanchili, Surya","U.S. Representative - District 04 - Jordan, Jim","U.S. Representative - District 04 - Kissick, Donald","U.S. Representative - District 04 - Litt, Doug","U.S. Representative - District 05 - Finkenbiner, Caleb","U.S. Representative - District 05 - Latta, Bob",...,"U.S. Representative - District 09 - Iott, Rich","U.S. Representative - District 09 - Kaptur, Marcy","U.S. Representative - District 15 - Buckel, Bill","U.S. Representative - District 15 - Kammerer, William","U.S. Representative - District 15 - Kilroy, Mary Jo","U.S. Representative - District 15 - Ryon, David","U.S. Representative - District 15 - Stivers, Steve","U.S. Representative - District 17 - Graham, Jim","U.S. Representative - District 17 - Ryan, Timothy","U.S. Representative - District 17 - Traficant, James"
35,Adams,3.0,619.0,5269.0,2289.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
157,Allen,0.0,0.0,0.0,0.0,24086.0,995.0,8299.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
210,Ashland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,972.0,2795.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
338,Ashtabula,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
409,Athens,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9767,Washington,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9853,Wayne,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9880,Williams,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2894.0,8517.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9978,Wood,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13271.0,27399.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10003,Wyandot,0.0,0.0,0.0,0.0,2778.0,147.0,853.0,734.0,2422.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
#89 rows is incorrect, 88 counties
df_house['COUNTY NAME'].nunique()

88

In [22]:
df_house['COUNTY NAME'].value_counts()
#Carroll county appears twice

COUNTY NAME
Carroll       2
Adams         1
Montgomery    1
Pickaway      1
Perry         1
             ..
Greene        1
Geauga        1
Gallia        1
Fulton        1
Wyandot       1
Name: count, Length: 88, dtype: int64

In [23]:
OH_Carroll = df_house.loc[(df_house['COUNTY NAME']=='Carroll')]
filter_Carroll = OH_Carroll.columns[OH_Carroll.ne(0).any()]
print(OH_Carroll[filter_Carroll])

    COUNTY NAME  U.S. Representative - District 18 - Gibbs, Bob  \
880     Carroll                                          5142.0
907     Carroll                                          5142.0

     U.S. Representative - District 18 - Space, Zack  \
880                                           4145.0
907                                           4145.0

     U.S. Representative - District 18 - Sutton, Lindsey
880                                              627.0
907                                              627.0

In [24]:
#with the above we can see that the rows are duplicates and we can safely drop one
# this also gives us the indices for these rows, so we will do this manually here

In [25]:
df_house = df_house.drop(index=907)
df_house = df_house.reset_index(drop=True)
df_house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 60 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   COUNTY NAME                                              88 non-null     object
 1   U.S. Representative - District 02 - Conover, Randy       88 non-null     float64
 2   U.S. Representative - District 02 - Johnston, Marc       88 non-null     float64
 3   U.S. Representative - District 02 - Schmidt, Jean        88 non-null     float64
 4   U.S. Representative - District 02 - Yalamanchili, Surya  88 non-null     float64
 5   U.S. Representative - District 04 - Jordan, Jim          88 non-null     float64
 6   U.S. Representative - District 04 - Kissick, Donald      88 non-null     float64
 7   U.S. Representative - District 04 - Litt, Doug           88 non-null     float64
 8   U.S. Representative - District 05 - Finkenbiner, Caleb   88 non-null     float64
 9   U.S. Representative - District 05 - Latta, Bob           88 non-null     float64
 10  U.S. Representative - District 05 - Smith, Brian         88 non-null     float64
 11  U.S. Representative - District 16 - Blevins, Jeffrey     88 non-null     float64
 12  U.S. Representative - District 16 - Boccieri, John       88 non-null     float64
 13  U.S. Representative - District 16 - Renacci, Jim         88 non-null     float64
 14  U.S. Representative - District 16 - Ross, Robert         88 non-null     float64
 15  U.S. Representative - District 14 - Jelenic, John        88 non-null     float64
 16  U.S. Representative - District 14 - LaTourette, Steven   88 non-null     float64
 17  U.S. Representative - District 14 - O'Neill, Bill        88 non-null     float64
 18  U.S. Representative - District 06 - Cadle, Richard       88 non-null     float64
 19  U.S. Representative - District 06 - Elsass, Martin       88 non-null     float64
 20  U.S. Representative - District 06 - Johnson, Bill        88 non-null     float64
 21  U.S. Representative - District 06 - Wilson, Charlie      88 non-null     float64
 22  U.S. Representative - District 18 - Gibbs, Bob           88 non-null     float64
 23  U.S. Representative - District 18 - Pitrone, Mark        88 non-null     float64
 24  U.S. Representative - District 18 - Space, Zack          88 non-null     float64
 25  U.S. Representative - District 18 - Sutton, Lindsey      88 non-null     float64
 26  U.S. Representative - District 01 - Berns, Jim           88 non-null     float64
 27  U.S. Representative - District 01 - Chabot, Steve        88 non-null     float64
 28  U.S. Representative - District 01 - Driehaus, Steve      88 non-null     float64
 29  U.S. Representative - District 01 - Stevenson, Rich      88 non-null     float64
 30  U.S. Representative - District 08 - Boehner, John        88 non-null     float64
 31  U.S. Representative - District 08 - Condit, James        88 non-null     float64
 32  U.S. Representative - District 08 - Coussoule, Justin    88 non-null     float64
 33  U.S. Representative - District 08 - Harlow, David        88 non-null     float64
 34  U.S. Representative - District 07 - Anderson, John       88 non-null     float64
 35  U.S. Representative - District 07 - Austria, Steve       88 non-null     float64
 36  U.S. Representative - District 07 - Conner, Bill         88 non-null     float64
 37  U.S. Representative - District 07 - Easton, David        88 non-null     float64
 38  U.S. Representative - District 03 - Roberts, Joe         88 non-null     float64
 39  U.S. Representative - District 03 - Turner, Mike         88 non-null     float64
 40  U.S. Representative - District 10 - Corrigan, Peter      88 non-null     float64
 41  U.S. Representative - District 10 - Goggins, Jeff        88 non-null     float64
 42  U.S. Representative - District 10 - Kucinich, Dennis     88 non-null     float64
 43  U.S. Representative - District 11 - Fudge, Marcia        88 non-null     float64
 44  U.S. Representative - District 11 - Pekarek, Thomas      88 non-null     float64
 45  U.S. Representative - District 13 - Ganley, Tom          88 non-null     float64
 46  U.S. Representative - District 13 - Sutton, Betty        88 non-null     float64
 47  U.S. Representative - District 12 - Brooks, Paula        88 non-null     float64
 48  U.S. Representative - District 12 - Irvine, Travis       88 non-null     float64
 49  U.S. Representative - District 12 - Tiberi, Pat          88 non-null     float64
 50  U.S. Representative - District 09 - Iott, Rich           88 non-null     float64
 51  U.S. Representative - District 09 - Kaptur, Marcy        88 non-null     float64
 52  U.S. Representative - District 15 - Buckel, Bill         88 non-null     float64
 53  U.S. Representative - District 15 - Kammerer, William    88 non-null     float64
 54  U.S. Representative - District 15 - Kilroy, Mary Jo      88 non-null     float64
 55  U.S. Representative - District 15 - Ryon, David          88 non-null     float64
 56  U.S. Representative - District 15 - Stivers, Steve       88 non-null     float64
 57  U.S. Representative - District 17 - Graham, Jim          88 non-null     float64
 58  U.S. Representative - District 17 - Ryan, Timothy        88 non-null     float64
 59  U.S. Representative - District 17 - Traficant, James     88 non-null     float64
dtypes: float64(59), object(1)
memory usage: 41.4+ KB

In [26]:
df_house

,COUNTY NAME,"U.S. Representative - District 02 - Conover, Randy","U.S. Representative - District 02 - Johnston, Marc","U.S. Representative - District 02 - Schmidt, Jean","U.S. Representative - District 02 - Yalamanchili, Surya","U.S. Representative - District 04 - Jordan, Jim","U.S. Representative - District 04 - Kissick, Donald","U.S. Representative - District 04 - Litt, Doug","U.S. Representative - District 05 - Finkenbiner, Caleb","U.S. Representative - District 05 - Latta, Bob",...,"U.S. Representative - District 09 - Iott, Rich","U.S. Representative - District 09 - Kaptur, Marcy","U.S. Representative - District 15 - Buckel, Bill","U.S. Representative - District 15 - Kammerer, William","U.S. Representative - District 15 - Kilroy, Mary Jo","U.S. Representative - District 15 - Ryon, David","U.S. Representative - District 15 - Stivers, Steve","U.S. Representative - District 17 - Graham, Jim","U.S. Representative - District 17 - Ryan, Timothy","U.S. Representative - District 17 - Traficant, James"
0,Adams,3.0,619.0,5269.0,2289.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Allen,0.0,0.0,0.0,0.0,24086.0,995.0,8299.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Ashland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,972.0,2795.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Ashtabula,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Athens,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,Washington,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84,Wayne,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85,Williams,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2894.0,8517.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86,Wood,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13271.0,27399.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87,Wyandot,0.0,0.0,0.0,0.0,2778.0,147.0,853.0,734.0,2422.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [27]:
#save this as a CSV
df_house.to_csv('OH_2010_house.csv')

In [28]:
#get list of all candidates
def get_candidates(data,delimiter='-'):
    """this function will get candidate names when the format is 'type of race - district - candidate name'"""
    cand_split = [cand.split(delimiter) for cand in data]
    cand_names = [cand[-1] for cand in cand_split]
    cand_names = [cand.strip() for cand in cand_names]
    return cand_names

In [29]:
#get list of all districts
def get_districts(data,delimiter='-'):
    """this function will get district names when the format is 'type of race - district - candidate name'"""
    data_split = [dist.split(delimiter) for dist in data]
    district_names = [dist[-2] for dist in data_split]
    district_names = [dist.strip() for dist in district_names]
    return district_names

In [30]:
cand_list = [col for col in df if col.startswith('U.S. Representative')]

In [31]:
candidates_2010 = get_candidates(cand_list,'-')

In [24]:
candidates_2010

['Conover, Randy',
 'Johnston, Marc',
 'Schmidt, Jean',
 'Yalamanchili, Surya',
 'Jordan, Jim',
 'Kissick, Donald',
 'Litt, Doug',
 'Finkenbiner, Caleb',
 'Latta, Bob',
 'Smith, Brian',
 'Blevins, Jeffrey',
 'Boccieri, John',
 'Renacci, Jim',
 'Ross, Robert',
 'Jelenic, John',
 'LaTourette, Steven',
 "O'Neill, Bill",
 'Cadle, Richard',
 'Elsass, Martin',
 'Johnson, Bill',
 'Wilson, Charlie',
 'Gibbs, Bob',
 'Pitrone, Mark',
 'Space, Zack',
 'Sutton, Lindsey',
 'Berns, Jim',
 'Chabot, Steve',
 'Driehaus, Steve',
 'Stevenson, Rich',
 'Boehner, John',
 'Condit, James',
 'Coussoule, Justin',
 'Harlow, David',
 'Anderson, John',
 'Austria, Steve',
 'Conner, Bill',
 'Easton, David',
 'Roberts, Joe',
 'Turner, Mike',
 'Corrigan, Peter',
 'Goggins, Jeff',
 'Kucinich, Dennis',
 'Fudge, Marcia',
 'Pekarek, Thomas',
 'Ganley, Tom',
 'Sutton, Betty',
 'Brooks, Paula',
 'Irvine, Travis',
 'Tiberi, Pat',
 'Iott, Rich',
 'Kaptur, Marcy',
 'Buckel, Bill',
 'Kammerer, William',
 'Kilroy, Mary Jo',
 'Ryon, David',
 'Stivers, Steve',
 'Graham, Jim',
 'Ryan, Timothy',
 'Traficant, James']

In [32]:
districts = pd.Series(get_districts(cand_list)).drop_duplicates().to_list()

In [37]:
districts

['District 02',
 'District 04',
 'District 05',
 'District 16',
 'District 14',
 'District 06',
 'District 18',
 'District 01',
 'District 08',
 'District 07',
 'District 03',
 'District 10',
 'District 11',
 'District 13',
 'District 12',
 'District 09',
 'District 15',
 'District 17']

In [33]:
len(districts)

18

In [24]:
#WE WANT:
    # COLUMNS - COUNTY, CONG_DIST, REP_VOTES, DEM_VOTES, dem_inc, rep_inc, total_votes, dem_less_rep_votes

In [34]:
house_cand_2010 = pd.read_csv(r'data/house_cand_party_2010.csv',index_col=0)

In [35]:
house_cand_2010

,STATE ABBREVIATION,DISTRICT,PARTY_INC,CANDIDATE NAME (First),CANDIDATE NAME (Last),CANDIDATE NAME(First Last),"CANDIDATE NAME (Last, First)"
0,AL,01,REP_1,Jo,Bonner,Jo Bonner,"Bonner, Jo"
1,AL,01,OTHER_0,David,Walter,David Walter,"Walter, David"
2,AL,02,REP_0,Martha,Roby,Martha Roby,"Roby, Martha"
3,AL,02,DEM_1,Bobby,Bright,Bobby Bright,"Bright, Bobby"
4,AL,03,REP_1,Mike,Rogers,Mike Rogers,"Rogers, Mike"
...,...,...,...,...,...,...,...
1709,WI,08,REP_0,Reid J.,Ribble,Reid J. Ribble,"Ribble, Reid J."
1710,WI,08,DEM_1,Steven L.,Kagen,Steven L. Kagen,"Kagen, Steven L."
1716,WY,00,REP_1,Cynthia M.,Lummis,Cynthia M. Lummis,"Lummis, Cynthia M."
1717,WY,00,DEM_0,David,Wendt,David Wendt,"Wendt, David"
1718,WY,00,OTHER_0,John V.,Love,John V. Love,"Love, John V."

In [36]:
house_cand_2010_simple = house_cand_2010[['CANDIDATE NAME (Last, First)','PARTY_INC']]

In [37]:
house_cand_2010_simple

     CANDIDATE NAME (Last, First) PARTY_INC
0                      Bonner, Jo     REP_1
1                   Walter, David   OTHER_0
2                    Roby, Martha     REP_0
3                   Bright, Bobby     DEM_1
4                    Rogers, Mike     REP_1
...                           ...       ...
1709              Ribble, Reid J.     REP_0
1710             Kagen, Steven L.     DEM_1
1716           Lummis, Cynthia M.     REP_1
1717                 Wendt, David     DEM_0
1718                Love, John V.   OTHER_0

[1521 rows x 2 columns]

In [161]:
def remove_middle_names(name):
    # Split the name by spaces
    parts = name.split(' ')
    
    # If the item has more than one space, keep only the first two parts
    if len(parts) > 2:
        return ' '.join(parts[:2])
    else:
        return name

In [163]:
#remove middele names from this df
house_cand_2010_simple['CANDIDATE NAME (Last, First)'] = house_cand_2010_simple['CANDIDATE NAME (Last, First)'].apply(lambda x : remove_middle_names(x))

C:\Users\joshu\AppData\Local\Temp\ipykernel_18832\371345468.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  house_cand_2010_simple['CANDIDATE NAME (Last, First)'] = house_cand_2010_simple['CANDIDATE NAME (Last, First)'].apply(lambda x : remove_middle_names(x)).copy()

In [164]:
house_cand_2010_simple

     CANDIDATE NAME (Last, First) PARTY_INC
0                      Bonner, Jo     REP_1
1                   Walter, David   OTHER_0
2                    Roby, Martha     REP_0
3                   Bright, Bobby     DEM_1
4                    Rogers, Mike     REP_1
...                           ...       ...
1709                 Ribble, Reid     REP_0
1710                Kagen, Steven     DEM_1
1716              Lummis, Cynthia     REP_1
1717                 Wendt, David     DEM_0
1718                   Love, John   OTHER_0

[1521 rows x 2 columns]

In [26]:
# for each column in each row, if column value > 0: 'col a' = col_name

In [30]:
keywords = ['District 02','COUNTY NAME']

In [31]:
# d2_OH2010 = df_house.filter(like='|'.join(keywords),axis=1)

In [32]:
# d2_OH2010

In [36]:
dist_2 = df_house[df_house.columns[df_house.columns.str.contains('|'.join(keywords))]]

In [37]:
dist_2

,COUNTY NAME,"U.S. Representative - District 02 - Conover, Randy","U.S. Representative - District 02 - Johnston, Marc","U.S. Representative - District 02 - Schmidt, Jean","U.S. Representative - District 02 - Yalamanchili, Surya"
0,Adams,3.0,619.0,5269.0,2289.0
1,Allen,0.0,0.0,0.0,0.0
2,Ashland,0.0,0.0,0.0,0.0
3,Ashtabula,0.0,0.0,0.0,0.0
4,Athens,0.0,0.0,0.0,0.0
...,...,...,...,...,...
83,Washington,0.0,0.0,0.0,0.0
84,Wayne,0.0,0.0,0.0,0.0
85,Williams,0.0,0.0,0.0,0.0
86,Wood,0.0,0.0,0.0,0.0
87,Wyandot,0.0,0.0,0.0,0.0

In [67]:
# threshold = len(dist_2.columns) / 2
# OH_2_2010 = dist_2[dist_2.apply(lambda row: (row == 0).sum() <= threshold, axis=1)]

In [68]:
# OH_2_2010

,COUNTY NAME,"U.S. Representative - District 02 - Conover, Randy","U.S. Representative - District 02 - Johnston, Marc","U.S. Representative - District 02 - Schmidt, Jean","U.S. Representative - District 02 - Yalamanchili, Surya"
0,Adams,3.0,619.0,5269.0,2289.0
7,Brown,0.0,1121.0,8010.0,4167.0
12,Clermont,61.0,5352.0,41034.0,17481.0
30,Hamilton,37.0,4767.0,49258.0,39770.0
65,Pike,2.0,521.0,4444.0,3392.0
72,Scioto,2.0,805.0,6601.0,5081.0
82,Warren,23.0,3074.0,24411.0,10251.0

In [38]:
OH_2_2010['DIST'] = 2
OH_2_2010['STATE'] = 'OH'

NameError: name 'OH_2_2010' is not defined

In [70]:
OH_2_2010

,COUNTY NAME,"U.S. Representative - District 02 - Conover, Randy","U.S. Representative - District 02 - Johnston, Marc","U.S. Representative - District 02 - Schmidt, Jean","U.S. Representative - District 02 - Yalamanchili, Surya",DIST,STATE
0,Adams,3.0,619.0,5269.0,2289.0,2,OH
7,Brown,0.0,1121.0,8010.0,4167.0,2,OH
12,Clermont,61.0,5352.0,41034.0,17481.0,2,OH
30,Hamilton,37.0,4767.0,49258.0,39770.0,2,OH
65,Pike,2.0,521.0,4444.0,3392.0,2,OH
72,Scioto,2.0,805.0,6601.0,5081.0,2,OH
82,Warren,23.0,3074.0,24411.0,10251.0,2,OH

In [165]:
df_house = pd.read_csv('OH_2010_house.csv',index_col=0)

In [166]:
new_columns = get_candidates(df_house)

In [167]:
df_house.columns = new_columns

In [136]:
df_house

,COUNTY NAME,"Conover, Randy","Johnston, Marc","Schmidt, Jean","Yalamanchili, Surya","Jordan, Jim","Kissick, Donald","Litt, Doug","Finkenbiner, Caleb","Latta, Bob",...,"Iott, Rich","Kaptur, Marcy","Buckel, Bill","Kammerer, William","Kilroy, Mary Jo","Ryon, David","Stivers, Steve","Graham, Jim","Ryan, Timothy","Traficant, James"
0,Adams,3.0,619.0,5269.0,2289.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Allen,0.0,0.0,0.0,0.0,24086.0,995.0,8299.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Ashland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,972.0,2795.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Ashtabula,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Athens,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,Washington,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84,Wayne,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85,Williams,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2894.0,8517.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86,Wood,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13271.0,27399.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87,Wyandot,0.0,0.0,0.0,0.0,2778.0,147.0,853.0,734.0,2422.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [137]:
house_cand_party = pd.read_csv(r'data/house_cand_party_2010.csv')

In [138]:
candidate_party_mapping = dict(zip(house_cand_party['CANDIDATE NAME (Last, First)'], house_cand_party['PARTY_INC']))

In [139]:
cand_list = list(house_cand_party['CANDIDATE NAME (Last, First)'])

In [84]:
cand_list

['Bonner, Jo',
 'Walter, David',
 'Roby, Martha',
 'Bright, Bobby',
 'Rogers, Mike',
 'Segrest, Steve',
 'Aderholt, Robert',
 'Brooks, Mo',
 'Raby, Steve',
 'Bachus, Spencer',
 'Sewell, Terri A.',
 'Chamberlain, Don',
 'Young, Don',
 'Crawford, Harry T., Jr.',
 'Faleomavaega, Eni F.H.',
 'Amata, Aumua',
 'Tuika, Tuika',
 'Gosar, Paul',
 'Kirkpatrick, Ann',
 'Patti, Nicole',
 'Franks, Trent',
 'Thrasher, John',
 'Gammill, Powell',
 'William, Crum ',
 'Quayle, Ben',
 'Hulburd, Jon',
 'Shoen, Michael',
 'Clark, Leonard ',
 'Pastor, Ed',
 'Contreras, Janet',
 'Cobb, Joe',
 'Dewitt, Rebecca',
 'Schweikert, David',
 'Mitchell, Harry',
 'Coons, Nick',
 'Flake, Jeff',
 'Schneider, Rebecca',
 'Tapp, Darell',
 'Grayson, Richard',
 'Grijalva, Raúl M.',
 'McClung, Ruth',
 'Myer, Harley',
 'Keane, George',
 'Giffords, Gabrielle',
 'Kelly, Jesse',
 'Stoltz, Steven',
 'Crawford, Rick',
 'Causey, Chad',
 'Adler, Ken',
 'Higgins, Mickey',
 'Griffin, Tim',
 'Elliott, Joyce',
 'Levi, Lance',
 'Kennedy, Lewis',
 'Suits, Danial',
 'Womack, Steve',
 'Whitaker, David',
 'Ross, Mike',
 'Rankin, Beth Anne',
 'Drake, Josh',
 'Thompson, Mike',
 'Hanks, Loren',
 'Wolman, Carol',
 'Rodrigues, Mike',
 'Herger, Wally ',
 'Reed, Jim',
 'Jensen, Mark A.',
 'Lungren, Dan',
 'Bera, Ami',
 'Leidecker, Jerry L.',
 'Tuma, Douglas Arthur',
 'Roskey, Mike',
 'McClintock, Tom ',
 'Curtis, Clint',
 'Emery, Benjamin "Ben"',
 'Matsui, Doris',
 'Smith, Paul A.',
 'Frink, Gerald Allen',
 'Lacy, Tony',
 'Woolsey, Lynn C.',
 'Judd, Jim',
 'Ruyle, Eugene E.',
 'Smollen, Joel',
 'Miller, George ',
 'Tubbs, Rick',
 'Pelosi, Nancy',
 'Dennis, John',
 'La Riva, Gloria E.',
 'Berg, Philip ',
 'Shields, Summer ',
 'Lee, Barbara',
 'Hashimoto, Gerald ',
 'Heller, Dave',
 'Eyer, James',
 'Allen, Larry',
 'Garamendi, John',
 'Clift, Gary',
 'Cloward, Jeremy',
 'McNerney, Jerry',
 'Harmer, David',
 'Christensen, David',
 'Speier, Jackie ',
 'Moloney, Mike',
 'Williams, Mark Paul',
 'Harding, Joseph Michael',
 'Stark, Fortney Pete',
 'Baker, Forest ',
 'Pareja, Chris',
 'Eshoo, Anna G.',
 'Chapman, Dave',
 'Lazaga, Paul',
 'Honda, Mike',
 'Kirkland, Scott',
 'Lofgren, Zoe',
 'Sahagun, Daniel',
 'Gonzalez, Edward ',
 'Farr, Sam',
 'Taylor, Jeff',
 'Petersen, Eric',
 'Larkin, Mary V.',
 'Kabat, Ronald P.',
 'Cardoza, Dennis',
 'Berryhill, Michael Clare, Sr.',
 'Denham, Jeff',
 'Goodwin, Loraine',
 'Marsden, Les',
 'Costa, Jim',
 'Vidak, Andy',
 'Nunes, Devin G.',
 'McCarthy, Kevin',
 'Uebersax, John',
 'Capps, Lois',
 'Watson, Tom ',
 'Hager, John V.',
 'Stafford, Darrell M.',
 'Gallegly, Elton',
 'Allison, Timothy J.',
 'McKeon, Howard P. "Buck"',
 'Conaway, Jackie ',
 'Dreier, David',
 'Warner, Russ',
 'Miller, David L.',
 'Weissbuch, Randall',
 'Sherman, Brad',
 'Reed, Mark',
 'Berman, Howard L. ',
 'Froyd, Merlin',
 'Rodriquez, Carlos A.',
 'Schiff, Adam B.',
 'Colbert, John P.',
 'Cushing, William P.',
 'Waxman, Henry A.',
 'Wilkerson, Charles E.',
 'Miller, Erich D.',
 'Castaldo, Richard R.',
 'Becerra, Xavier',
 'Genoves, Sal',
 'Smith, Stephen C.',
 'Chu, Judy',
 'Schmerling, Edward "Ed"',
 'Bass, Karen',
 'Andion, James L.',
 'Evans, Mervin Leon ',
 'Roybal-Allard, Lucille',
 'Miller, Wayne',
 'Waters, Maxine',
 'Brown, K. Bruce',
 'Edmondson, Suleiman Charles',
 'Harman, Jane',
 'Fein, Mattie',
 'Peters, Herb',
 'Richardson, Laura',
 'Parker, Star ',
 'Dibs, Nicholas',
 'Napolitano, Grace F.',
 'Vaughn, Robert',
 'Sanchez, Linda T.',
 'Andre, Larry S.',
 'Smith, John A.',
 'Royce, Ed',
 'Avalos, Christina',
 'Lewis, Jerry',
 'Meagher, Pat',
 'Zander, Pamela',
 'Miller, Gary G.',
 'Williamson, Michael',
 'Lambert, Mark',
 'Baca, Joe',
 'Folkens, Scott',
 'Calvert, Ken',
 'Hedrick, Bill',
 'Mack, Mary Bono',
 'Pougnet, Steve ',
 'Lussenheide, Bill',
 'Rohrabacher, Dana',
 'Arnold, Ken',
 'Shah, Jay A.',
 'Sanchez, Loretta',
 'Tran, Van',
 'Iglesias, Cecilia "Ceci"',
 'Campbell, John',
 'Krom, Beth',
 'Binkley, Mike',
 'Issa, Darrell',
 'Katz, Howard',
 'Clark, Dion',
 'Paster, Mike ',
 'Bilbray, Brian P.',
 'Busby, Francine',
 'Grossmith, Lars',
 'Clark, Miriam E.',
 'Filner, Bob',
 'Popaditch, Nick',
 'Shapiro, Marcus Jay',
 'Hunter, Duncan D.',
 'Lutz, Ray ',
 'Benoit, Michael',
 'Davis, Susan A.',
 'Crimmins, Michael',
 'Dekker, Paul',
 'DeGette, Diana',
 'Fallon, Mike',
 'Swing, Gary',
 'Jones, Clint',
 'Styskal, Chris',
 'Polis, Jared',
 'Bailey, Stephen',
 'Goss, Jenna',
 'Harris, Curtis',
 'Raibourn, Henry',
 'Tipton, Scott R.',
 'Salazar, John',
 'Gilman, Gregory',
 'Segrest, Jake',
 'Hargis, John W., Sr',
 'Fritz, James',
 'Gardner, Cory',
 'Markey, Betsy',
 'Aden, Doug',
 'Waszkiewicz, Ken "Wasko"',
 'Lamborn, Doug',
 'Bradley, Kevin',
 'Scott, Brian "Barron X"',
 'Klaver, Jerell',
 'Coffman, Mike',
 'Flerlage, John',
 'McNealy, Rob',
 'Kearns, Michael Shawn',
 'Perlmutter, Ed',
 'Frazier, Ryan',
 'Bailey, Buck',
 'Larson, John B.',
 'Larson, John B.',
 'Brickley, Ann',
 'Krayeske, Kenneth J.',
 'Hutchinson, Christopher J.',
 'Stepanek, Daniel J.',
 'Courtney, Joe',
 'Courtney, Joe',
 'Peckinpaugh, Janet',
 'Deshefy, G. Scott',
 'Reale, Daniel',
 'Bianchi, Muriel P.',
 'DeLauro, Rosa L.',
 'DeLauro, Rosa L.',
 'Labriola, Jerry, Jr.',
 'Pillsbury, Charles A.',
 'Itshaky, Boaz',
 'Himes, Jim',
 'Himes, Jim',
 'Debicella, Dan',
 'Flanagan, Eugene',
 'Murphy, Chris',
 'Murphy, Chris',
 'Caligiuri, Sam S. F.',
 'Caligiuri, Sam S. F.',
 'Pistone, John',
 'Smith, Elmon',
 'Carney, John C., Jr.',
 'Urquhart, Glen',
 'Lofland, Earl R.',
 'Wangen, Brent A.',
 'Brown, Jeffrey',
 'Coons, Christopher A.',
 "O'Donnell, Christine",
 'Miller, Glenn A.',
 'Rash, James W., Jr.',
 'Bourgeois, Maurice F.',
 'Devard, Samtra',
 'Norton, Eleanor Holmes',
 'Smith, Missy Reilly',
 'Tingling-Clemmons, Rick',
 'Noble, Queen',
 'Miller, Jeff',
 'Cantrell, Joe',
 'Krause, John',
 'Bryan, Jim',
 'Southerland, Steve',
 'Boyd, Allen',
 'McKain, Paul C.',
 'Berryhill, Dianne',
 'Netherwood, Ray',
 'Brown, Corinne',
 'Yost, Michael "Mike"',
 'Martin-Back, Terry',
 'Crenshaw, Ander',
 'Stanley, Troy D.',
 'Pueschel, Deborah "Deb" Katz',
 'Koniz, Gary L.',
 'Nugent, Richard B. "Rich"',
 'Piccillo, James "Jim"',
 'Stearns, Clifford B. "Cliff"',
 'Schonberg, Steve',
 'Mica, John L.',
 'Beaven, Heather',
 'Webster, Daniel',
 'Grayson, Alan',
 'Dunmire, Peg',
 'Metcalfe, George L.',
 'Gerritzen, Steven J.',
 'Bilirakis, Gus Michael',
 'de Palma, Anita',
 'Young, C.W. Bill',
 'Justice, Charlie',
 'Castor, Kathy',
 'Prendergast, Mike',
 'Ross, Dennis A.',
 'Edwards, Lori',
 'Wilkinson, Randy',
 'Buchanan, Vern',
 'Golden, James T.',
 'Mack, Connie',
 'Roach, James Lloyd',
 'St. Claire, William Maverick',
 'Posey, Bill',
 'Roberts, Shannon',
 'Rooney, Tom',
 'Horn, Jim',
 'Dean, William',
 'Wilson, Frederica S.',
 'Vereen, Roderick D.',
 'Ros-Lehtinen, Ileana',
 'Banciella, Rolando A.',
 'Deutch, Ted',
 'Budd, Joe',
 'Smilan, Stan',
 'Schultz, Debbie Wasserman',
 'Harrington, Karen',
 'Blumenthal, Stanley',
 'Kunst, Robert',
 'Schock, Clayton',
 'Diaz-Balart, Mario',
 'West, Allen',
 'Klein, Ron',
 'Hastings, Alcee L.',
 'Sansaricq, Bernard',
 'Adams, Sandra "Sandy"',
 'Kosmas, Suzanne',
 'Ruiz, Nicholas, III',
 'Rivera, David',
 'Garcia, Joe',
 'Arrojo, Roly',
 'Porter, Craig',
 'Kingston, Jack',
 'Harris, Oscar L., II',
 'Bishop, Sanford',
 'Keown, Mike',
 'Westmoreland, Lynn',
 'Saunders, Frank',
 'Johnson, Hank, Jr.',
 'Carter, Lisbeth "Liz"',
 'Lewis, John',
 'Little, Fenn',
 'Price, Tom',
 'Woodall, Rob',
 'Heckman, Doug',
 'Scott, Austin',
 'Marshall, Jim',
 'Graves, Tom',
 'Broun, Paul',
 'Edwards, Russell',
 'Gingrey, Phil',
 'Barrow, John',
 'Mckinney, Raymond',
 'Scott, David',
 'Crane, Mike',
 'Bordallo, Madeleine Z.',
 'Hanabusa, Colleen ',
 'Djou, Charles ',
 'Hirono, Mazie',
 'Willoughby, John W.',
 'Brock, Pat',
 'Von Sonn, Andrew Vsevolod ',
 'Labrador, Raul R.',
 'Minnick, Walt',
 'Olson, Dave ',
 'Washburn, Mike ',
 'Simpson, Mike',
 'Crawford, Mike',
 'Schad, Brian ',
 'Rush, Bobby L.',
 'Wardingley, Raymond G.',
 'Adams, Jeff',
 'Jackson, Jesse L., Jr.',
 'Hayes, Isaac C.',
 'Williams, Anthony W.',
 'Lipinski, Daniel William',
 'Bendas, Michael A.',
 'Schmidt, Laurel Lambert',
 'Gutierrez, Luis V.',
 'Vasquez, Israel',
 'Burns, Robert J.',
 'Quigley, Mike',
 'Ratowitz, David',
 'Reichel, Matthew',
 'Roskam, Peter J.',
 'Lowe, Benjamin S.',
 'Davis, Danny K.',
 'Weiman, Mark M.',
 'Clemons, Clarence Desmond',
 'Walsh, Joe ',
 'Bean, Melissa',
 'Scheurer, Bill',
 'Schakowsky, Janice D.',
 'Pollak, Joel Barry',
 'Ribeiro, Simon',
 'Dold, Robert',
 'Seals, Daniel J.',
 'Brumfield, Author C.',
 'Kinzinger, Adam',
 'Halvorson, Deborah "Debbie"',
 'Costello, Jerry F.',
 'Newman, Teri',
 'Jennings, Rodger W.',
 'Biggert, Judy',
 'Harper, Scott',
 'Hultgren, Randall M. "Randy"',
 'Foster, Bill',
 'Kairis, Daniel J.',
 'Marks, Doug',
 'Johnson, Timothy V.',
 'Gill, David',
 'Manzullo, Donald A.',
 'Gaulrapp, George W.',
 'Campbell, Terry G.',
 'Schilling, Bobby',
 'Hare, Phil',
 'Davis, Roger K.',
 'Schock, Aaron',
 'Hirner, Deirdre "DK"',
 'Schafer, Sheldon',
 'Shimkus, John M.',
 'Bagwell, Tim',
 'Kirk, Mark Steven',
 'Giannoulias, Alexander "Alexi"',
 'Jones, LeAlan M.',
 'Labno, Mike',
 'Zadek, Robert L. "Bob"',
 'Boyd, Will',
 'Dabney, Corey',
 'Atanus, Susanne',
 'Horton, Shon-Tiyon "Santiago"',
 'Nagar, Avner',
 'Jagla, Stan',
 'Raichart, Darren',
 'Seida, Lowell M.',
 'Kirk, Mark Steven',
 'Giannoulias, Alexander "Alexi"',
 'Jones, LeAlan M.',
 'Labno, Mike',
 'Zadek, Robert',
 'Boyd, Will',
 'Pinkney, Ina',
 'Dabney, Corey',
 'Atanus, Susanne',
 'Horton, Shon-Tiyon "Santiago"',
 'Jagla, Stan',
 'Seida, Lowell M.',
 'Visclosky, Peter J. ',
 'Leyva, Mark',
 'Morris, Jon ',
 'Donnelly, Joe',
 'Walorski, Jackie  ',
 'Vogel, Mark ',
 'Stutzman, Marlin A. #',
 'Hayhurst, Thomas',
 'Wise, Scott ',
 'Metzger, Tom',
 'Stephens, Wes',
 'Stutzman, Marlin A.',
 'Hayhurst, Thomas',
 'Wise, Scott',
 'Rokita, Todd',
 'Sanders, David',
 'Duncan, John ',
 'Burton, Dan',
 'Crawford, Tim',
 'Reid, Richard (Chard)',
 'Trueblood, Jesse C.',
 'Pence, Mike',
 'Welsh, Barry ',
 'Thompson, Talmage (T.J.), Jr.',
 'Carson, Andre D.',
 'Scott, Marvin B.',
 'Wilson, Dav',
 'Bucshon, Larry D. ',
 'VanHaaften, W. Trent',
 'Cunningham, John ',
 'Young, Todd',
 'Hill, Baron P.',
 'Knott, Greg "No Bull"',
 'Lucas, Jerry R.',
 'Braley, Bruce',
 'Lange, Benjamin M.',
 'Petsche, Rob J.',
 'Faulkner, Jason A. ',
 'Loebsack, Dave ',
 'Miller-Meeks, Mariannette',
 'Sicard, Gary ',
 'Tack, Jon',
 'Boswell, Leonard L. ',
 'Zaun, Brad ',
 'Williamson, Rebecca ',
 'Latham, Tom ',
 'Maske, Bill ',
 'Lensing, Dan ',
 'King, Steve  ',
 'Campbell, Matthew ',
 'Monroe, Martin James',
 'Huelskamp, Tim\xa0',
 'Jilka, Alan\xa0',
 'Warner, Jack\xa0',
 'Jenkins, Lynn\xa0',
 'Hudspeth, Cheryl\xa0',
 'Garrard, Robert\xa0',
 'Yoder, Kevin\xa0',
 'Moore, Stephene\xa0',
 'Talbert, Jasmin\xa0',
 'Pompeo, Mike\xa0',
 'Goyle, Raj\xa0',
 'Ducey, Susan\xa0G.\xa0',
 'Smith, Shawn',
 'Whitfield, Edward ',
 'Hatchett, Charles Kendall',
 'Guthrie, S. Brett',
 'Marksberry, Ed',
 'Yarmuth, John',
 'Lally, Todd',
 'Martin, Edward A.',
 'Hansen, Michael D.',
 'Davis, Geoff',
 'Waltz, John',
 'Rogers, Harold "Hal"',
 'Holbert, James E. "Jim"',
 'Chandler, Ben',
 'Barr, Garland "Andy"',
 'Collins, C. Wes',
 'Vance, Randolph S.',
 'Scalise, "Steve"',
 'Katz, Myron ',
 'Wells, Arden',
 'Richmond, Cedric',
 'Cao, "Joseph"',
 'Marquize, Anthony ',
 'Radosta, "Jack" ',
 'Landry, "Jeff" ',
 'Sangisetty, Ravi',
 'Fleming, John',
 'Melville, David ',
 'Cash, Artis ',
 'Alexander, Rodney ',
 'Gibbs, "Tom," Jr.',
 'Cassidy, William "Bill"',
 'McDonald, Merritt E., Sr.',
 'Boustany, Charles W., Jr.',
 'Pingree, Chellie',
 'Scontras, Dean Peter',
 'Horton, Walter',
 'Lowberg, Alan',
 'Michaud, Michael H.',
 'Levesque, Jason J.',
 'Harris, Andy',
 'Kratovil, Frank M., Jr.',
 'Davis, Richard James',
 'Wilson, Jack N.',
 'Kennedy, Michael',
 'Ruppersberger, C.A. Dutch',
 'Cardarelli, Marcelo',
 'Gaztanaga, Lorenzo',
 'Sarbanes, John',
 'Wilhelm, Jim',
 'McKinley, Jerry',
 'Lareau, Alain',
 'Edwards, Donna',
 'Broadus, Robert',
 'Hoyer, Steny H.',
 'Lollar, Charles',
 'Shickle, H. Gavin',
 'Bartlett, Roscoe G.',
 'Duck, Andrew ',
 'Massey, Dan',
 'Reed, Michael',
 'Cummings, Elijah',
 'Mirabile, Frank, Jr.',
 'Bly, Ray',
 'Spencer, Scott',
 'Dickson, Fred Donald, Jr.',
 'Van Hollen, Chris',
 'Philips, Michael Lee',
 'Grannis, Mark',
 'Nordhorn, Fred',
 'Olver, John W.',
 'Gunn, William L., Jr',
 'Engel, Michael',
 'Neal, Richard E.',
 'Wesley, Thomas A. ',
 'McGovern, James P.',
 'Lamb, Martin A.',
 'Barron, Patrick J.',
 'Frank, Barney',
 'Bielat, Sean DM',
 'Allen, Susan F.',
 'Jordan, Donald M.',
 'Tsongas, Nicola S.',
 'Golnik, Jonathan A.',
 'Brown, Dale E.',
 'Clark, Robert M.',
 'Tierney, John F.',
 'Hudak, Bill',
 'Markey, Edward J.',
 'Dembrowski, Gerry',
 'Capuano, Michael E.',
 'Lynch, Stephen F.',
 'Harrison, Vernon M.',
 'Dunkelbarger, Philip',
 'Keating, William R.',
 'Perry, Jeffrey Davis ',
 'Lewis, Maryanne',
 'Sheets, James A.',
 'Van Nes, Joe',
 'Benishek, Dan',
 'McDowell, Gary',
 'Wilson, Glenn A.',
 'Lambert, Patrick',
 'Shelton, Keith',
 'Boal, Ellis',
 'Huizenga, Bill',
 'Johnson, Fred',
 'Graeser, Ronald E.',
 'Clarke, Lloyd',
 'Gillotte, Joseph',
 'Amash, Justin',
 'Miles, Pat',
 'Rogers, James',
 'Gerrard, Ted',
 'Shick, Charlie',
 'Camp, Dave',
 'Campbell, Jerry M.',
 'Emerick, John',
 'Foster, Clint',
 'Kildee, Dale',
 'Kupiec, John',
 'de Hues, Matthew J.',
 'Moon, Michael J.',
 'Upton, Fred',
 'Cooney, Don',
 'Valkner, Melvin D.',
 'Strand, Fred',
 'Foster, Pat',
 'Walberg, Tim',
 'Schauer, Mark',
 'Aughney, Scott Eugene',
 'Merle, Greg',
 'Wunsch, Richard',
 'Davis, Danny',
 'Rogers, Mike',
 'Harvey, Eric',
 'Enderle, Lance #',
 'Dashairya, Bhagwan',
 'Peters, Gary',
 'Raczkowski, Rocky',
 'Goodman, Adam',
 'Campbell, Douglas',
 'Gray, Bob',
 'Kuofie, Matthew ',
 'Miller, Candice S.',
 'Yanez, Henry',
 'Beavers, Claude',
 'Caveny, Candace R.',
 'McCotter, Thaddeus G.',
 'Mosher, Natalie',
 'Tatar, John J.',
 'Levin, Sander',
 'Volaric, Don',
 'Williams, Julia',
 'Schwartz, Leonard',
 'Townsend, Les',
 'Jacquemotte, Alan',
 'Clarke, Hansen',
 'Hauler, John',
 'Corsetti, George',
 'Montgomery, Duane',
 'Peterson, Heidi ',
 'Conyers, John, Jr.',
 'Ukrainec, Don',
 'Sosnowski, Marc J.',
 'Secula, Richard J.',
 'Dingell, John D.',
 'Steele, Rob',
 'Smith, Aimee',
 'Morgan, Kerry Lee ',
 'Furman, Matthew',
 'Walz, Tim',
 'Demmer, Randy',
 'Wilson, Steven',
 'Johnson, Lars',
 'Kline, John',
 'Madore, Shelley',
 'Paulsen, Erik',
 'Meffert, Jim',
 'Oleson, Jon',
 'McCollum, Betty',
 'Collett, Teresa',
 'Shepard, Jack',
 'Carlson, Steve',
 'Ellison, Keith',
 'Demos, Joel',
 'Torgerson, Lynne',
 'Schrunk, Tom',
 'Cavlan, Michael James',
 'Bachmann, Michele',
 'Clark, Tarryl',
 'Anderson, Bob',
 'Immelman, Aubrey',
 'Peterson, Collin C.',
 'Byberg, Lee',
 'Waldorf, Gene',
 'Menze, Glen R.',
 'Cravaack, Chip',
 'Oberstar, James L.',
 'Olson, Timothy',
 'Burton, Richard (George)',
 'Nunnelee,  Alan ',
 'Childers, Travis W.',
 'Pang, Wally ',
 'Green, Les',
 'Baddley, A.G. ',
 'Giaramita, Gail ',
 "Hoskins, Rick 'Rico'",
 'Taylor, Harold M.',
 'Washer, Barbara Dale ',
 'Thompson, Bennie G',
 'Marcy, Bill ',
 'Norwood, Ashley',
 'Harper, Gregg',
 'Gill, Joel L.',
 "Hill, Tracella Lou O'Hara",
 'Palazzo, Steven',
 'Taylor, Gene',
 "Hampton, Kenneth 'Tim'",
 'Revies, Anna Jewel ',
 'Clay, Lacy',
 'Hamlin, Robyn',
 'Stone, Julie',
 'Akin, Todd',
 'Lieber, Arthur',
 'Mosbacher, Steve',
 'Cannon, Patrick M.',
 'Carnahan, Russ',
 'Martin, Ed ',
 'Hedrick, Steven R.',
 'Ivanovich, Nicholas J. (Nick)',
 'Wallner, Brian',
 'Hartzler, Vicky',
 'Skelton, Ike',
 'Braun, Jason Michael',
 'Cowan, Greg',
 'Cleaver, Emanuel, II',
 'Turk, Jacob',
 'Langkraehr, Randall D. (Randy)',
 'Lay, Dave',
 'Graves, Sam',
 'Hylton, Clint',
 'Yarber, Kyle',
 'Long, Billy',
 'Eckersley, Scott',
 'Craig, Kevin',
 'Ladendorf, Nicholas Ivan',
 'Emerson, Jo Ann',
 'Sowers, Tommy',
 'Bill, Larry',
 'Vandeven, Rick',
 'Luetkemeyer, Blaine',
 'Dwyer, Christopher W.',
 'Reed, Clifford Jeffery (Jeff)',
 'Burrus, Ron',
 'Rehberg, Denny',
 'McDonald, Dennis',
 'Fellows, Mike',
 'Fortenberry, Jeff',
 'Harper, Ivy',
 'Terry, Lee',
 'White, Tom',
 'Smith, Adrian',
 'Davis, Rebekah',
 'Hill, Dan ',
 'Berkley, Shelley',
 'Wegner, Kenneth A.',
 'Hansen, Jonathan J.',
 'Klapproth, Ed',
 'Heller, Dean ',
 'Price, Nancy',
 'Best, Russell ',
 'Heck, Joe',
 'Titus, Dina ',
 'Michaels, Barry ',
 'Silvestri, Joseph P.',
 'Narter, Scott David ',
 'Guinta, Frank C. ',
 'Shea-Porter, Carol ',
 'Hodson, Philip',
 'Bass, Charles ',
 'Kuster, Ann McLane',
 'vanBlommesteyn, Tim',
 'Wilson, Howard L.',
 'Andrews, Robert E.',
 'Glading, Dale',
 'Heacock, Mark',
 'Chapman, Margaret M.',
 'Petrutz, Nicky I.',
 'LoBiondo, Frank A. ',
 'Stein, Gary',
 'Boyce, Peter F.',
 'Valdes-Munoz, Vitov',
 'Lovett, Mark',
 'Runyan, Jon',
 'Adler, John A.',
 'DeStefano, Peter',
 'Conger, Russ',
 'Donahue, Lawrence J. ',
 'Smith, Christopher H.',
 'Kleinhendler, Howard',
 'Siano, Joe',
 'Welzer, Steven ',
 'Meiswinkle, David R.',
 'Garrett, Scott',
 'Theise, Tod',
 'Fanning, Ed',
 'Quick, Mark D.',
 'Radigan, James Douglas ',
 'Pallone, Frank, Jr.',
 'Little, Anna C.',
 'Freudenheim, Jack',
 'Zaletal, Karen Anne',
 'Lance, Leonard',
 'Potosnak, Ed',
 'Pascrell, Bill, Jr.',
 'Straten, Roland',
 'Giangrasso, Raymond',
 'Rothman, Steven R.',
 'Agosta, Michael A.',
 'Alessandrini, Patricia',
 'Payne, Donald M.',
 'Alonso, Michael J.',
 'Toussaint, Robert Louis',
 'Miller, Joanne',
 'Frelinghuysen, Rodney P.',
 'Herbert, Douglas',
 'Gawron, Jim',
 'Holt, Rush',
 'Sipprelle, Scott',
 'Cody, Kenneth J.',
 'Sires, Albio ',
 'Dwyer, Henrietta ',
 'Zanowic, Anthony',
 'Nacer, Maximo Gomez',
 'Heinrich, Martin T.',
 'Barela, Jonathan L.',
 'Pearce, Steve',
 'Teague, Harry ',
 'Lujan, Ben R.',
 'Mullins, Thomas E.',
 'Bishop, Timothy H.',
 'Bishop, Timothy H.',
 'Bishop, Timothy H.',
 'Altschuler, Randolph',
 'Altschuler, Randolph',
 'Israel, Steve J.',
 'Israel, Steve J.',
 'Israel, Steve J.',
 'Gomez, John B.',
 'Gomez, John B.',
 'Tolda, Anthony',
 'King, Peter T.',
 'King, Peter T.',
 'King, Peter T.',
 'King, Peter T.',
 'Kudler, Howard A.',
 'McCarthy, Carolyn',
 'McCarthy, Carolyn',
 'Becker, Francis X., Jr.',
 'Becker, Francis X., Jr.',
 'Becker, Francis X., Jr.',
 'Becker, Francis X., Jr.',
 'Ackerman, Gary L.',
 'Ackerman, Gary L.',
 'Ackerman, Gary L.',
 'Milano, James',
 'Berney, Elizabeth',
 'Milano, James',
 'Meeks, Gregory W.',
 'Taub, Asher E.',
 'Taub, Asher E.',
 'Crowley, Joseph',
 'Crowley, Joseph',
 'Reynolds, Kenneth A.',
 'Reynolds, Kenneth A.',
 'Gronowicz, Anthony',
 'Nadler, Jerrold L.',
 'Nadler, Jerrold L.',
 'Kone, Susan L.',
 'Kone, Susan L.',
 'Weiner, Anthony D.',
 'Weiner, Anthony D.',
 'Weiner, Anthony D.',
 'Turner, Robert L.',
 'Turner, Robert L.',
 'Towns, Edolphus',
 'Muniz, Diana',
 'Johnson, Ernest',
 'Clarke, Yvette D.',
 'Clarke, Yvette D.',
 'Carr, Hugh C.',
 'Carr, Hugh C.',
 'Velazquez, Nydia M.',
 'Velazquez, Nydia M.',
 'Gaffney, Alice',
 'Grimm, Michael G.',
 'Grimm, Michael G.',
 'McMahon, Michael E.',
 'McMahon, Michael E.',
 'Vendittelli, Tom',
 'Maloney, Carolyn B.',
 'Maloney, Carolyn B.',
 'Brumberg, David Ryan',
 'Healy, Timothy J.',
 'LaVerghetta, Dino L.',
 'Rangel, Charles B.',
 'Rangel, Charles B.',
 'Faulkner, Michel J.',
 'Faulkner, Michel J.',
 'Faulkner, Michel J.',
 'Schley, Craig',
 'Schley, Craig',
 'Calero, Roger',
 'Serrano, Jose E.',
 'Serrano, Jose E.',
 'Della Valle, Frank',
 'Della Valle, Frank',
 'Engel, Eliot L.',
 'Engel, Eliot L.',
 'Mele, Anthony',
 'Kleinhandler, York J.',
 'Lowey, Nita M.',
 'Lowey, Nita M.',
 'Lowey, Nita M.',
 'Russell, Jim',
 'Russell, Jim',
 'Hayworth, Nan',
 'Hayworth, Nan',
 'Hayworth, Nan',
 'Hall, John J.',
 'Hall, John J.',
 'Gibson, Christopher P.',
 'Gibson, Christopher P.',
 'Murphy, Scott',
 'Murphy, Scott',
 'Murphy, Scott',

In [85]:
# This code will now create columns for each party in the merged_df dataframe and sum the votes for candidates belonging to the same party. 
# The resulting party_votes_df will have the total votes for each party in each county. Adjust the column names based on your actual data.

In [86]:
# # Function to add group totals to the county data
# def add_group_totals(county_data, candidate_groups):
#     # Merge dataframes based on the 'Candidate' column
#     merged_data = pd.merge(county_data, candidate_groups, left_on='Candidate', right_on='Candidate', how='left')

#     # Drop the 'Candidate' column as it is no longer needed
#     merged_data = merged_data.drop('Candidate', axis=1)

#     # Group by 'County' and 'Group', summing up the values
#     grouped_data = merged_data.groupby(['County', 'Group']).sum().reset_index()

#     # Pivot the table to have 'County' as index and 'Group' as columns
#     pivoted_data = grouped_data.pivot(index='County', columns='Group', values=grouped_data.columns[2:])

#     # Replace NaN values with 0
#     pivoted_data = pivoted_data.fillna(0)

#     # Add the group totals to the original county data
#     county_data = pd.merge(county_data, pivoted_data, left_on='County', right_index=True, how='left')

#     return county_data

# # Call the function and print the result
# result = add_group_totals(county_data, candidate_groups)
# print(result)

In [168]:
df_house

,COUNTY NAME,"Conover, Randy","Johnston, Marc","Schmidt, Jean","Yalamanchili, Surya","Jordan, Jim","Kissick, Donald","Litt, Doug","Finkenbiner, Caleb","Latta, Bob",...,"Iott, Rich","Kaptur, Marcy","Buckel, Bill","Kammerer, William","Kilroy, Mary Jo","Ryon, David","Stivers, Steve","Graham, Jim","Ryan, Timothy","Traficant, James"
0,Adams,3.0,619.0,5269.0,2289.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Allen,0.0,0.0,0.0,0.0,24086.0,995.0,8299.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,Ashland,0.0,0.0,0.0,0.0,0.0,0.0,0.0,972.0,2795.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,Ashtabula,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Athens,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,Washington,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84,Wayne,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
85,Williams,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2894.0,8517.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
86,Wood,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13271.0,27399.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
87,Wyandot,0.0,0.0,0.0,0.0,2778.0,147.0,853.0,734.0,2422.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [169]:
county_names = list(df_house['COUNTY NAME'])

In [170]:
df_t = df_house.drop('COUNTY NAME',axis=1)

In [171]:
df_t = df_t.transpose(copy=True)

In [172]:
df_t = df_t.reset_index().copy()

In [173]:
county_names.insert(0,'CANDIDATE NAME (Last, First)')

In [152]:
county_names

['CANDIDATE NAME (Last, First)',
 'Adams',
 'Allen',
 'Ashland',
 'Ashtabula',
 'Athens',
 'Auglaize',
 'Belmont',
 'Brown',
 'Butler',
 'Carroll',
 'Champaign',
 'Clark',
 'Clermont',
 'Clinton',
 'Columbiana',
 'Coshocton',
 'Crawford',
 'Cuyahoga',
 'Darke',
 'Defiance',
 'Delaware',
 'Erie',
 'Fairfield',
 'Fayette',
 'Franklin',
 'Fulton',
 'Gallia',
 'Geauga',
 'Greene',
 'Guernsey',
 'Hamilton',
 'Hancock',
 'Hardin',
 'Harrison',
 'Henry',
 'Highland',
 'Hocking',
 'Holmes',
 'Huron',
 'Jackson',
 'Jefferson',
 'Knox',
 'Lake',
 'Lawrence',
 'Licking',
 'Logan',
 'Lorain',
 'Lucas',
 'Madison',
 'Mahoning',
 'Marion',
 'Medina',
 'Meigs',
 'Mercer',
 'Miami',
 'Monroe',
 'Montgomery',
 'Morgan',
 'Morrow',
 'Muskingum',
 'Noble',
 'Ottawa',
 'Paulding',
 'Perry',
 'Pickaway',
 'Pike',
 'Portage',
 'Preble',
 'Putnam',
 'Richland',
 'Ross',
 'Sandusky',
 'Scioto',
 'Seneca',
 'Shelby',
 'Stark',
 'Summit',
 'Trumbull',
 'Tuscarawas',
 'Union',
 'Van Wert',
 'Vinton',
 'Warren',
 'Washington',
 'Wayne',
 'Williams',
 'Wood',
 'Wyandot']

In [174]:
df_t.columns = county_names

In [175]:
df_t.head()

,"CANDIDATE NAME (Last, First)",Adams,Allen,Ashland,Ashtabula,Athens,Auglaize,Belmont,Brown,Butler,...,Tuscarawas,Union,Van Wert,Vinton,Warren,Washington,Wayne,Williams,Wood,Wyandot
0,"Conover, Randy",3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,23.0,0.0,0.0,0.0,0.0,0.0
1,"Johnston, Marc",619.0,0.0,0.0,0.0,0.0,0.0,0.0,1121.0,0.0,...,0.0,0.0,0.0,0.0,3074.0,0.0,0.0,0.0,0.0,0.0
2,"Schmidt, Jean",5269.0,0.0,0.0,0.0,0.0,0.0,0.0,8010.0,0.0,...,0.0,0.0,0.0,0.0,24411.0,0.0,0.0,0.0,0.0,0.0
3,"Yalamanchili, Surya",2289.0,0.0,0.0,0.0,0.0,0.0,0.0,4167.0,0.0,...,0.0,0.0,0.0,0.0,10251.0,0.0,0.0,0.0,0.0,0.0
4,"Jordan, Jim",0.0,24086.0,0.0,0.0,0.0,13073.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2778.0

In [179]:
df_t = df_t.merge(house_cand_2010_simple,how='left',on='CANDIDATE NAME (Last, First)')

In [182]:
df_group = df_t.groupby('PARTY_INC').sum()

In [183]:
df_group

,"CANDIDATE NAME (Last, First)",Adams,Allen,Ashland,Ashtabula,Athens,Auglaize,Belmont,Brown,Butler,...,Tuscarawas,Union,Van Wert,Vinton,Warren,Washington,Wayne,Williams,Wood,Wyandot
PARTY_INC,,,,,,,,,,,,,,,,,,,,,
DEM_0,"Yalamanchili, SuryaLitt, DougFinkenbiner, Cale...",2289.0,8299.0,972.0,11716.0,0.0,2867.0,0.0,4167.0,35864.0,...,0.0,0.0,1965.0,0.0,18882.0,0.0,0.0,2894.0,13271.0,1587.0
DEM_1,"Boccieri, JohnWilson, CharlieSpace, ZackDrieha...",0.0,0.0,3806.0,0.0,10926.0,0.0,11185.0,0.0,1990.0,...,12451.0,0.0,0.0,2018.0,0.0,7719.0,12677.0,0.0,0.0,0.0
OTHER_0,"Conover, RandyJohnston, MarcKissick, DonaldSmi...",622.0,995.0,1361.0,1553.0,764.0,604.0,1058.0,1121.0,4223.0,...,1599.0,911.0,487.0,211.0,3097.0,733.0,2691.0,701.0,2340.0,348.0
REP_0,"Renacci, JimJohnson, BillGibbs, BobChabot, Ste...",0.0,0.0,8235.0,0.0,5283.0,0.0,11324.0,0.0,7315.0,...,15181.0,13004.0,0.0,2008.0,0.0,12714.0,20847.0,0.0,0.0,0.0
REP_1,"Schmidt, JeanJordan, JimLatta, BobLaTourette, ...",5269.0,24086.0,2795.0,16773.0,0.0,13073.0,0.0,8010.0,69652.0,...,0.0,0.0,7575.0,0.0,56337.0,0.0,0.0,8517.0,27399.0,5200.0