In [1]:
# Libraries for getting the data
import numpy as np
import pandas as pd
# from docx import Document
from src.modules import * #contains functions used in common with processing election and IRS data
import os

In [2]:
# Filepath to our formatted datasets (see 'merge_State_IRS_data.py' for how these were generated)
datasets_filepath = 'data/house_fec_irs_joined/' 

datasets= [file for file in os.listdir(datasets_filepath) if os.path.isfile(os.path.join(datasets_filepath, file))]

In [3]:
# Filepath to our formatted datasets (see 'merge_State_IRS_data.py' for how these were generated)
datasets_filepath = 'data/house_fec_irs_joined/' 

datasets= [file for file in os.listdir(datasets_filepath) if os.path.isfile(os.path.join(datasets_filepath, file))]

### NOTE: Due to the nameing conventions used in merge_State_IRS_data.py, every even-indexed dataframe ([0),[2],[4],[6]..(etc. etc.) will be the election data merged with the IRS data from that year
### Every odd-indexed dataframe will contain the election data for that year merged with the IRS data from that year LESS the values from the previous year.

# Name an empty dataframe for the .csvs containing only IRS data from the year of the election
house_IRS_f = pd.DataFrame()

# Iterate through the list of csv files, merging the appropriate ones
for i in range(0, len(datasets), 2): #selects ever-other dataframe, starting with the first.
    csv_file = datasets[i]
    data = pd.read_csv(os.path.join(datasets_filepath, csv_file))
    house_IRS_f = pd.concat([house_IRS_f, data], axis=0, ignore_index=True)
    
# Drop any null columns (The number of columns in the IRS data increases year-to-year, bureaucratically)
house_IRS_f = house_IRS_f.dropna(axis=1)

In [4]:
# Name an empty dataframe for .csvs containing IRS data LESS the previous year's data
house_IRS_d = pd.DataFrame()

# Iterate through the list of csv files, merging the appropriate ones
for i in range(1, len(datasets), 2): #selects ever-other dataframe, starting with the first.
    csv_file = datasets[i]
    data = pd.read_csv(os.path.join(datasets_filepath, csv_file))
    house_IRS_d = pd.concat([house_IRS_d, data], axis=0, ignore_index=True)
    
# Drop any null columns (The number of columns in the IRS data increases year-to-year, bureaucratically)
house_IRS_d = house_IRS_d.dropna(axis=1)

In [6]:
# These columns are not needed for the machine learning portion
house_IRS_f2 = house_IRS_f.drop(['STATE','County'],axis=1)
house_IRS_d2 = house_IRS_d.drop(['STATE','County'],axis=1)

In [7]:
# Take the log of our data
house_IRS_f_log = house_IRS_f2.apply(np.log)
house_IRS_d_log = house_IRS_d2.apply(np.log)

In [12]:
# replace any inf. values with zero values 
house_IRS_f_log = house_IRS_f_log.replace([np.inf, -np.inf, np.nan], 0)
house_IRS_d_log = house_IRS_d_log.replace([np.inf, -np.inf, np.nan], 0)

In [14]:
# Write data
house_IRS_f_log.to_csv('../data/logarithm_of_joined_data/house_IRS_f_log.csv', index=False)
house_IRS_d_log.to_csv('../data/logarithm_of_joined_data/house_IRS_d_log.csv', index=False)

In [13]:
house_IRS_f_log

,D0,D1,OTHER0,R0,R1,N1,MARS1,MARS2,MARS4,PREP,...,N11070,A11070,N06500,A06500,N10300,A10300,N11901,A11901,N11902,A11902
0,11.618708,13.919673,11.363567,12.721996,11.574218,14.735746,14.033746,13.496379,13.117974,14.182567,...,12.906642,13.229696,14.293272,17.017937,14.412163,17.059085,12.864965,14.488941,14.502549,15.627119
1,11.418318,10.356854,8.031060,11.000415,11.187500,12.668044,11.816136,11.812289,10.651596,12.102322,...,10.507257,10.841775,12.319714,14.763726,12.383675,14.799227,10.707057,12.271172,12.465124,13.604209
2,0.000000,0.000000,8.549660,10.217203,0.000000,10.831312,10.003785,9.829841,9.128045,10.352651,...,8.980927,9.292750,10.404263,12.428248,10.485424,12.478844,8.743532,10.350798,10.645187,11.700400
3,12.033206,9.441611,7.039660,9.688436,12.163254,13.048868,12.281041,12.179523,10.767010,12.455040,...,10.642086,11.049015,12.721289,15.643620,12.783809,15.676627,11.343560,13.189936,12.762885,13.883896
4,11.309266,0.000000,0.000000,0.000000,11.454449,12.369126,11.492927,11.472312,10.548494,11.822247,...,10.600627,11.066670,11.942693,14.494214,12.012002,14.528768,10.407289,12.128895,12.159453,13.281498
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,9.047115,0.000000,0.000000,0.000000,10.042597,10.286366,9.528067,9.311090,7.965546,9.563108,...,8.016318,8.536996,9.882264,11.908583,9.939337,11.975936,8.313852,9.615472,10.074495,11.088385
946,9.573663,0.000000,0.000000,0.000000,10.546262,10.926298,10.151519,9.997888,8.345218,10.372866,...,8.597851,9.259416,10.547707,12.637530,10.611523,12.724161,9.171600,11.038239,10.651123,11.605158
947,8.293800,0.000000,0.000000,0.000000,9.558388,9.839482,9.076809,8.784162,7.610853,9.308374,...,7.682482,8.253488,9.439068,11.245412,9.499272,11.326391,7.915713,9.122601,9.620461,10.606461
948,10.160414,0.000000,0.000000,0.000000,10.603288,11.071470,10.349775,10.028357,8.637639,10.380963,...,8.484670,9.014082,10.756199,13.123199,10.798759,13.179052,9.344871,10.899476,10.809526,11.801857
949,7.760893,0.000000,0.000000,0.000000,9.092570,9.336973,8.548692,8.296547,7.012115,8.855093,...,6.966024,7.560080,8.979669,10.925255,9.027619,11.002500,7.467371,8.867850,9.098291,10.077525